server:
  port: 6543

spring:
  profiles:
    active: win
  application:
    name: simple-lottery-api

wx:
  config:
    originalid: gh_95b2229b90fb
    appid: wx470537fb2f5bf897
    token: yysimple

